services:
  postgres:
    container_name: factoriesPGDB
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5431:5432

  pgadmin:
    container_name: factoriesPGAdmin
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15433:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
    - postgres

volumes:
  postgres:
  pgadmin: